const CartActionTypes={
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    DECREASE_QUANTITY:'DECREASE_QUANTITY',
    CART_ITEM_REMOVE:'CART_ITEM_REMOVE'
};

export default CartActionTypes;